INSERT INTO estado (id, nome, uf, codigo) VALUES (1, 'Acre', 'AC', '12');
INSERT INTO estado (id, nome, uf, codigo) VALUES (2, 'Alagoas', 'AL', '27');
INSERT INTO estado (id, nome, uf, codigo) VALUES (3, 'Amazonas', 'AM', '13');
INSERT INTO estado (id, nome, uf, codigo) VALUES (4, 'Amapá', 'AP', '16');
INSERT INTO estado (id, nome, uf, codigo) VALUES (5, 'Bahia', 'BA', '29');
INSERT INTO estado (id, nome, uf, codigo) VALUES (6, 'Ceará', 'CE', '23');
INSERT INTO estado (id, nome, uf, codigo) VALUES (7, 'Distrito Federal', 'DF', '53');
INSERT INTO estado (id, nome, uf, codigo) VALUES (8, 'Espírito Santo', 'ES', '32');
INSERT INTO estado (id, nome, uf, codigo) VALUES (9, 'Goiás', 'GO', '52');
INSERT INTO estado (id, nome, uf, codigo) VALUES (10, 'Maranhão', 'MA', '21');
INSERT INTO estado (id, nome, uf, codigo) VALUES (11, 'Minas Gerais', 'MS', '31');
INSERT INTO estado (id, nome, uf, codigo) VALUES (12, 'Mato Grosso do Sul', 'MS', '50');
INSERT INTO estado (id, nome, uf, codigo) VALUES (13, 'Mato Grosso', 'MT', '51');
INSERT INTO estado (id, nome, uf, codigo) VALUES (14, 'Pará', 'PA', '15');
INSERT INTO estado (id, nome, uf, codigo) VALUES (15, 'Paraíba', 'PB', '25');
INSERT INTO estado (id, nome, uf, codigo) VALUES (16, 'Pernambuco', 'PE', '16', '2');
INSERT INTO estado (id, nome, uf, codigo) VALUES (17, 'Piauí', 'PI', '22');
INSERT INTO estado (id, nome, uf, codigo) VALUES (18, 'Paraná', 'PR', '41');
INSERT INTO estado (id, nome, uf, codigo) VALUES (19, 'Rio de Janeiro', 'RJ', '33');
INSERT INTO estado (id, nome, uf, codigo) VALUES (20, 'Rio Grande do Norte', 'RN', '24');
INSERT INTO estado (id, nome, uf, codigo) VALUES (21, 'Rondônia', 'RO', '11');
INSERT INTO estado (id, nome, uf, codigo) VALUES (22, 'Roraima', 'RR', '14');
INSERT INTO estado (id, nome, uf, codigo) VALUES (23, 'Rio Grande do Sul', 'RS', '43');
INSERT INTO estado (id, nome, uf, codigo) VALUES (24, 'Santa Catarina', 'SC', '42');
INSERT INTO estado (id, nome, uf, codigo) VALUES (25, 'Sergipe', 'SE', '28');
INSERT INTO estado (id, nome, uf, codigo) VALUES (26, 'São Paulo', 'SP', '35');
INSERT INTO estado (id, nome, uf, codigo) VALUES (27, 'Tocantins', 'TO', '17');
INSERT INTO estado (id, nome, uf, codigo) VALUES (28, 'EXTERIOR', 'EX', '18');
